// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/16/2025, 7:46:30 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/gabriel/Documents/dev/Infra-Site/hyperion/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gabriel/Documents/dev/Infra-Site/hyperion/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gabriel/Documents/dev/Infra-Site/hyperion/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gabriel/Documents/dev/Infra-Site/hyperion/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gabriel/Documents/dev/Infra-Site/hyperion/app/plugins/**/*.{js,ts,mjs}","/home/gabriel/Documents/dev/Infra-Site/hyperion/app/composables/**/*.{js,ts,mjs}","/home/gabriel/Documents/dev/Infra-Site/hyperion/app/utils/**/*.{js,ts,mjs}","/home/gabriel/Documents/dev/Infra-Site/hyperion/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gabriel/Documents/dev/Infra-Site/hyperion/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/gabriel/Documents/dev/Infra-Site/hyperion/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/gabriel/Documents/dev/Infra-Site/hyperion/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;